cards = [
  { printing = "otc/326", at = "useful non-basic lands" },  # Sunscorched Divide
  { printing = "woc/172", at = "useful non-basic lands" },  # Temple of the False God
  { printing = "dmc/223", at = "useful non-basic lands" },  # Opulent Palace
  { printing = "soc/130", qty = 2, at = "useful non-basic lands" },  # Fabled Passage
  { printing = "soc/58", at = "useful non-basic lands" },  # Turbulent Steppe
  { printing = "soc/54", at = "useful non-basic lands" },  # Scorched Geyser
  { printing = "c21/80", qty = 2, at = "useful non-basic lands" },  # Study Hall
  { printing = "soc/386", at = "useful non-basic lands" },  # Mistveil Plains
  { printing = "soc/369", qty = 2, at = "useful non-basic lands" },  # Exotic Orchard
  { printing = "ecc/158", at = "useful non-basic lands" },  # Path of Ancestry
  { printing = "soc/407", at = "useful non-basic lands" },  # Study Hall
  { printing = "soc/129", qty = 2, at = "useful non-basic lands" },  # Command Tower
  { printing = "blc/300", at = "useful non-basic lands" },  # Clifftop Retreat
  { printing = "soc/368", at = "useful non-basic lands" },  # Emeria, the Sky Ruin
  { printing = "cmm/990", at = "useful non-basic lands" },  # Cascade Bluffs
  { printing = "dmc/238", at = "useful non-basic lands" },  # Temple of Triumph
  { printing = "tdc/361", at = "useful non-basic lands" },  # Ferrous Lake
  { printing = "soc/57", at = "useful non-basic lands" },  # Turbulent Springs
  { printing = "ecc/23", at = "useful non-basic lands" },  # Rain-Slicked Copse
  { printing = "c17/267", qty = 3, at = "useful non-basic lands" },  # Opulent Palace
  { printing = "soc/59", at = "useful non-basic lands" },  # Turbulent Wilderness
  { printing = "m19/254", at = "useful non-basic lands" },  # Reliquary Tower
  { printing = "soc/401", at = "useful non-basic lands" },  # Rugged Prairie
  { printing = "soc/396", at = "useful non-basic lands" },  # Radiant Summit
  { printing = "m20/249", at = "useful non-basic lands" },  # Lotus Field
  { printing = "eoc/22", at = "useful non-basic lands" },  # Glittering Massif
  { printing = "soc/375", at = "useful non-basic lands" },  # Furycalm Snarl
  { printing = "bro/257", at = "useful non-basic lands" },  # Battlefield Forge
  { printing = "moc/403", at = "useful non-basic lands" },  # Frostboil Snarl
  { printing = "soc/378", at = "useful non-basic lands" },  # Hall of Oracles
  { printing = "woe/260", at = "useful non-basic lands" },  # Restless Spire
  { printing = "m3c/375", at = "useful non-basic lands" },  # Shivan Reef
  { printing = "frc/84", at = "useful non-basic lands" },  # Sulfur Falls
  { printing = "eoc/187", at = "useful non-basic lands" },  # Temple of Epiphany
  { printing = "rix/186", at = "shit lands" },  # Evolving Wilds
  { printing = "sos/265", qty = 3, at = "shit lands" },  # Terramorphic Expanse
  { printing = "sos/266", qty = 2, at = "shit lands" },  # Titan's Grave
  { printing = "sos/256", at = "shit lands" },  # Forum of Amity
  { printing = "sos/262", qty = 2, at = "shit lands" },  # Spectacle Summit
  { printing = "rna/247", at = "shit lands" },  # Gateway Plaza
  { printing = "grn/246", qty = 3, at = "shit lands" },  # Dimir Guildgate
  { printing = "c18/234", at = "shit lands" },  # Azorius Guildgate
  { printing = "c18/244", qty = 2, at = "shit lands" },  # Dismal Backwater
  { printing = "clu/234", at = "shit lands" },  # Dimir Guildgate
  { printing = "c18/272", at = "shit lands" },  # Orzhov Guildgate
  { printing = "scd/308", at = "shit lands" },  # Meandering River
  { printing = "frf/174", qty = 2, at = "shit lands" },  # Tranquil Cove
  { printing = "c19/230", at = "shit lands" },  # Bloodfell Caves
  { printing = "c19/279", at = "shit lands" },  # Swiftwater Cliffs
  { printing = "ktk/246", qty = 2, at = "shit lands" },  # Tranquil Cove
  { printing = "ema/246", qty = 3, at = "shit lands" },  # Thornwood Falls
  { printing = "fdn/266", at = "shit lands" },  # Scoured Barrens
  { printing = "grn/245", qty = 2, at = "shit lands" },  # Dimir Guildgate
  { printing = "m20/251", at = "shit lands" },  # Scoured Barrens
  { printing = "m20/258", at = "shit lands" },  # Thornwood Falls
  { printing = "grn/256", at = "shit lands" },  # Selesnya Guildgate
  { printing = "thb/249", at = "shit lands" },  # Unknown Shores
  { printing = "m20/243", at = "shit lands" },  # Blossoming Sands
  { printing = "m20/260", at = "shit lands" },  # Wind-Scarred Crag
  { printing = "znc/141", at = "shit lands" },  # Submerged Boneyard
  { printing = "rvr/276", at = "shit lands" },  # Dimir Guildgate
  { printing = "ddi/36", at = "shit lands" },  # Sejiri Refuge
  { printing = "hob/186", qty = 2, at = "shit lands" },  # Lake-town
  { printing = "tdm/267", at = "shit lands" },  # Scoured Barrens
  { printing = "frf/168", at = "shit lands" },  # Dismal Backwater
  { printing = "m13/224", at = "shit lands" },  # Evolving Wilds
  { printing = "mm2/241", at = "shit lands" },  # Evolving Wilds
  { printing = "m20/248", qty = 2, at = "shit lands" },  # Jungle Hollow
  { printing = "hob/182", qty = 2, at = "shit lands" },  # Elvenking's Halls
  { printing = "hob/184", at = "shit lands" },  # Hobbit Hole
  { printing = "soc/394", at = "shit lands" },  # Prismari Campus
  { printing = "soc/387", at = "shit lands" },  # Molten Tributary
  { printing = "sos/255", at = "shit lands" },  # Fields of Strife
  { printing = "soc/384", at = "shit lands" },  # Lorehold Campus
  { printing = "soc/402", at = "shit lands" },  # Sacred Peaks
  { printing = "neo/243", at = "stables" },  # Containment Construct
  { printing = "soc/354", at = "stables" },  # Perpetual Timepiece
  { printing = "soc/347", qty = 2, at = "stables" },  # Fellwar Stone
  { printing = "ema/226", at = "stables" },  # Millikin
  { printing = "soc/352", at = "stables" },  # Mind Stone
  { printing = "soc/353", at = "stables" },  # Patchwork Banner
  { printing = "soc/127", qty = 2, at = "stables" },  # Arcane Signet
  { printing = "soc/128", qty = 2, at = "stables" },  # Sol Ring
  { printing = "soc/345", at = "stables" },  # Currency Converter
  { printing = "soc/343", at = "stables" },  # Bitterthorn, Nissa's Animus
  { printing = "soc/350", at = "stables" },  # Lightning Greaves
  { printing = "soc/357", at = "stables" },  # Talisman of Creativity
  { printing = "soc/351", at = "stables" },  # Millikin
  { printing = "soc/355", at = "stables" },  # Solemn Simulacrum
  { printing = "hob/2", qty = 2, at = "colorless" },  # Old Thrush
  { printing = "hob/180", at = "colorless" },  # Well-Worn Spatula
  { printing = "hob/173", at = "stables" },  # Giant's Boulder
  { printing = "hob/1", at = "colorless" },  # Long-Bodied Grey Dog
  { printing = "hob/172", at = "colorless" },  # Dwarven Mattock
  { printing = "tdm/243", at = "colorless" },  # Jade-Cast Sentinel
  { printing = "clb/297", at = "colorless" },  # Arcane Encyclopedia
  { printing = "xln/239", qty = 9, at = "colorless" },  # Gilded Sentinel
  { printing = "xln/242", qty = 9, at = "colorless" },  # Pirate's Cutlass
  { printing = "xln/240", qty = 5, at = "colorless" },  # Hierophant's Chalice
  { printing = "clb/318", at = "stables" },  # Lantern of Revealing
  { printing = "clb/327", at = "stables" },  # Moss Diamond
  { printing = "clb/334", at = "stables" },  # Prized Statue
  { printing = "clb/442", at = "stables" },  # Charcoal Diamond
  { printing = "clb/305", at = "stables" },  # Charcoal Diamond
  { printing = "clb/330", at = "stables" },  # Nimblewright Schematic
  { printing = "thb/241", qty = 5, at = "colorless" },  # Wings of Hubris
  { printing = "xln/233", qty = 5, at = "colorless" },  # Cobbled Wings
  { printing = "thb/231", qty = 2, at = "colorless" },  # Altar of the Pantheon
  { printing = "grn/236", qty = 3, at = "colorless" },  # Glaive of the Guildpact
  { printing = "m20/234", at = "colorless" },  # Pattern Matcher
  { printing = "xln/237", qty = 2, at = "colorless" },  # Elaborate Firecannon
  { printing = "m20/221", at = "colorless" },  # Anvilwrought Raptor
  { printing = "dom/228", at = "colorless" },  # Shield of the Realm
  { printing = "nph/163", at = "colorless" },  # Trespassing Souleater
  { printing = "kld/232", qty = 2, at = "colorless" },  # Self-Assembler
  { printing = "bfz/224", at = "colorless" },  # Hedron Blade
  { printing = "dom/231", at = "colorless" },  # Sorcerer's Wand
  { printing = "m21/237", at = "colorless" },  # Silent Dart
  { printing = "ogw/165", at = "colorless" },  # Seer's Lantern
  { printing = "rix/184", at = "colorless" },  # Traveler's Amulet
  { printing = "thb/239", qty = 2, at = "colorless" },  # Thundering Chariot
  { printing = "bbd/247", at = "colorless" },  # Stone Golem
  { printing = "kld/217", qty = 2, at = "colorless" },  # Glassblower's Puzzleknot
  { printing = "m20/241", at = "colorless" },  # Vial of Dragonfire
  { printing = "aer/150", qty = 2, at = "colorless" },  # Filigree Crawler
  { printing = "kld/197", at = "colorless" },  # Bastion Mastodon
  { printing = "m19/237", at = "colorless" },  # Gearsmith Guardian
  { printing = "m20/237", qty = 2, at = "colorless" },  # Salvager of Ruin
  { printing = "grn/234", qty = 2, at = "colorless" },  # Dimir Locket
  { printing = "aer/156", at = "colorless" },  # Implement of Examination
  { printing = "sos/250", at = "colorless" },  # Page, Loose Leaf
  { printing = "sos/249", at = "colorless" },  # Mage Tower Referee
  { printing = "sos/3", at = "colorless" },  # Sundering Archaic
  { printing = "ktk/225", at = "colorless" },  # Sultai Banner
  { printing = "aer/159", at = "colorless" },  # Implement of Malice
  { printing = "arc/113", at = "colorless" },  # Obelisk of Esper
  { printing = "soc/299", at = "stables" },  # Brudiclad, Telchor Engineer
  { printing = "soc/5", at = "stables" },  # Muddle, the Ever-Changing
  { printing = "stx/189", at = "stables" },  # Galazeth Prismari
  { printing = "soc/295", at = "stables" },  # Balefire Liege
  { printing = "soc/49", at = "stables" },  # Lorehold Archivist // Restore Relic
  { printing = "stx/186", at = "stables" },  # Expressive Iteration
  { printing = "soc/329", at = "stables" },  # Rootha, Mercurial Artist
  { printing = "lcc/279", at = "stables" },  # Prismari Command
  { printing = "soc/8", at = "stables" },  # Rootha, Mastering the Moment
  { printing = "soc/314", at = "stables" },  # Hofri Ghostforge
  { printing = "soc/327", at = "stables" },  # Quintorius, Loremaster
  { printing = "stx/246", at = "stables" },  # Venerable Warsinger
  { printing = "soc/48", at = "stables" },  # Inspired Skypainter // Maestro's Gift
  { printing = "soc/337", at = "stables" },  # Veyran, Voice of Duality
  { printing = "stx/220", at = "bulk multicolor" },  # Quintorius, Field Historian
  { printing = "soc/321", at = "stables" },  # Mortality Spear
  { printing = "soc/328", at = "stables" },  # Rip Apart
  { printing = "soc/331", at = "stables" },  # Stormcatch Mentor
  { printing = "soc/2", at = "stables" },  # Excava, the Risen Past
  { printing = "soc/7", at = "stables" },  # Quintorius, History Chaser
  { printing = "soc/318", at = "stables" },  # Magma Opus
  { printing = "sos/191", at = "stables" },  # Geometer's Arthropod
  { printing = "soc/305", at = "stables" },  # Dina, Soul Steeper
  { printing = "sos/198", at = "stables" },  # Kirol, History Buff // Pack a Punch
  { printing = "sos/200", at = "stables" },  # Lorehold Charm
  { printing = "sos/211", at = "stables" },  # Prismari Charm
  { printing = "clb/415", at = "stables" },  # Bane, Lord of Darkness
  { printing = "clb/270", at = "stables" },  # Commander Liara Portyr
  { printing = "clb/269", at = "stables" },  # Cadira, Caller of the Small
  { printing = "ala/162", at = "bulk multicolor" },  # Carrion Thrash
  { printing = "grn/219", at = "bulk multicolor" },  # Vernadi Shieldmate
  { printing = "thb/227", qty = 3, at = "bulk multicolor" },  # Slaughter-Priest of Mogis
  { printing = "sos/177", qty = 2, at = "stables" },  # Bogwater Lumaret
  { printing = "sos/209", qty = 2, at = "stables" },  # Pest Mascot
  { printing = "sos/224", qty = 2, at = "stables" },  # Scolding Administrator
  { printing = "xln/218", qty = 2, at = "stables" },  # Belligerent Brontodon
  { printing = "grn/172", qty = 2, at = "bulk multicolor" },  # Garrison Sergeant
  { printing = "grn/155", qty = 2, at = "bulk multicolor" },  # Beamsplitter Mage
  { printing = "grn/210", qty = 5, at = "bulk multicolor" },  # Undercity Uprising
  { printing = "grn/158", qty = 7, at = "bulk multicolor" },  # Centaur Peacemaker
  { printing = "sos/196", at = "bulk multicolor" },  # Inkling Mascot
  { printing = "grn/198", at = "bulk multicolor" },  # Skyknight Legionnaire
  { printing = "sos/195", at = "bulk multicolor" },  # Imperious Inkmage
  { printing = "bfz/218", at = "bulk multicolor" },  # Resolute Blademaster
  { printing = "m20/213", at = "bulk multicolor" },  # Lightning Stormkin
  { printing = "frf/153", at = "bulk multicolor" },  # Grim Contest
  { printing = "sos/240", at = "bulk multicolor" },  # Vibrant Outburst
]

[places]
"useful non-basic lands" = {}
"shit lands" = {}
stables = {}
colorless = {}
"bulk multicolor" = {}
